template = "https://github.com/giellalt/template-lang-und"
rev_id = 294
template_sha = "a620868b33dee503846060f7bd6c6e88f3c1f6d1"

[replacements]
__GLOTTOLOG_ID__ = "luok1236"
__REPO__ = "lang-luo"
__UND2C__ = "luo"
__UNDEFINED__ = "Luo (Kenya and Tanzania)"
__UND__ = "luo"
